### ISSUE TITLE
Doesn't even work, able to login without even using captcha

### ISSUE THREAD

**Issue by roast247** [RahulDey12/laravel-captcha#6]
### **Here is where I put the validation**

```php
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Providers\RouteServiceProvider;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

use Rahul900day\Captcha\Facades\Captcha;
use Rahul900day\Captcha\Rules\Captcha as CaptchaRule;
use Illuminate\Support\Facades\Validator;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */
    use AuthenticatesUsers;
    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = RouteServiceProvider::HOME;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
  protected function validatorLogin(Request $request)
    {
   	Validator::make($request, [
   	 'email' => 'required|string',
         'password' => 'required|string',
   	  Captcha::getResponseName() => [
        	'required', 
        	new CaptchaRule(),
   	   ],
	]);
    }
    
}
```

### **And it doesn't even work**

**Comment by RahulDey12** [comment]
when you using controller you can use like this.

```php
use Rahul900day\Captcha\Facades\Captcha;
use Rahul900day\Captcha\Rules\Captcha as CaptchaRule;


protected function validatorLogin(Request $request)
{
    $request->validate([
        'email' => 'required|string',
        'password' => 'required|string',
        Captcha::getResponseName() => [
            'required',
            new CaptchaRule(),
        ],
    ]);
}

```

**Comment by roast247** [comment]
Still doesn't work. I added it and even when I press the login button it logs me in without saying the captcha is required.

**Comment by roast247** [comment]
I'm able to just login, it isn't requiring me to do the captcha

**Comment by roast247** [comment]
this is my login controller


<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Providers\RouteServiceProvider;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

use Rahul900day\Captcha\Facades\Captcha;
use Rahul900day\Captcha\Rules\Captcha as CaptchaRule;
use Illuminate\Support\Facades\Validator;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = RouteServiceProvider::HOME;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
    
  protected function validatorLogin(Request $request)
    {
   	$request->validate([
   	 'email' => 'required|string',
         'password' => 'required|string',
   	  Captcha::getResponseName() => [
        	'required', 
        	new CaptchaRule(),
   	   ],
	]);
    }
    
}

**Comment by roast247** [comment]
Can I get some help please????

**Comment by roast247** [comment]
Hello?

**Comment by RahulDey12** [comment]
@roast247 I will look after you on the weekend. Till then please wait.

**Comment by roast247** [comment]
it is the weekend

**Comment by roast247** [comment]
So how do I fix it?

**Comment by RahulDey12** [comment]
It's actually working fine. As I checked.

**Comment by roast247** [comment]
No it doesn't. As I've said before. I can still login without having to do the captcha. which makes the captcha useless! Please help!

**Comment by roast247** [comment]
please help

**Comment by roast247** [comment]
?

**Comment by RahulDey12** [comment]
Have you used the correct configuration? Because as I checked I can see that it is working fine. Which captcha provider are you using and what are your configuration.

**Comment by roast247** [comment]
I gave you my config files. I am using hcaptcha

**Comment by roast247** [comment]
This is not working

**Comment by roast247** [comment]
Please help!!!!!!!!!!!!!!!!!!!

**Comment by RahulDey12** [comment]
> I gave you my config files. I am using hcaptcha

1. Are you using Localhost ?
2. in `.env` did you give the correct keys ?

**Comment by roast247** [comment]
You are not reading what I am saying. The damn thing shows up just fine. When    I    Try      To      Login       In       ,       It      Is      Not       Requiring        Me        To      Do      The        Captcha

**Comment by roast247** [comment]
It shows up fine, but I can login without using captcha.

**Comment by roast247** [comment]
I’m gonna repeat it again. 
It shows up fine, but I can login without using captcha.

**Comment by roast247** [comment]
the fact that this is taking 14 days is crazy. Just help me for once

**Comment by RahulDey12** [comment]
I am willing to help your but the thing is that I am not able to reproduce the same issue you have.

**Comment by roast247** [comment]
Please make a video tutorial on setting up the whole thing

**Comment by roast247** [comment]
please

**Comment by roast247** [comment]
?

**Comment by roast247** [comment]
?

**Comment by roast247** [comment]
hello?

**Comment by roast247** [comment]
Please make a video tutorial on setting up the whole thing

**Comment by roast247** [comment]
hello?

**Comment by roast247** [comment]
Stop ignoring, please help! Make a video on installation!

**Comment by roast247** [comment]
hello?

**Comment by roast247** [comment]
you're really bad at replying
